# Generated by Django 5.1.3 on 2024-11-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDName', models.CharField(max_length=100, verbose_name='product name:')),
                ('PRDDesc', models.TextField(max_length=100, verbose_name='product decription:')),
                ('PRDPrice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='product price:')),
                ('PRDCost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='product cost:')),
                ('PRDCreated', models.DateTimeField(verbose_name='product created:')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
