# Generated by Django 5.1.3 on 2024-11-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDCreated',
            field=models.DateTimeField(verbose_name='product created at:'),
        ),
    ]
