# Generated by Django 5.1.3 on 2024-11-28 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productimage_prdiproduct_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categoryies'},
        ),
        migrations.AlterField(
            model_name='category',
            name='CATParent',
            field=models.ForeignKey(blank=True, limit_choices_to={'CATParent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='category perant :'),
        ),
        migrations.CreateModel(
            name='Product_Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PACCAccessories', models.ManyToManyField(related_name='accessories', to='product.product', verbose_name='accessories')),
                ('PACCProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_accessories', to='product.product', verbose_name='accessories product')),
            ],
            options={
                'verbose_name': 'Product_accssesories',
                'verbose_name_plural': 'Product_accssesories',
            },
        ),
        migrations.CreateModel(
            name='Product_ALternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PALTAlternative', models.ManyToManyField(related_name='alternative', to='product.product', verbose_name='alternative')),
                ('PALTProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_alternative', to='product.product', verbose_name='alternative product')),
            ],
            options={
                'verbose_name': 'Product_ALternative',
                'verbose_name_plural': 'Product_ALternatives',
            },
        ),
    ]
