# Generated by Django 5.1.3 on 2024-11-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_prdslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDDiscountPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='product discountprice:'),
        ),
    ]
