# Generated by Django 5.1.3 on 2024-11-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_prddiscountprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDBestseller',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDNew',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
