# Generated by Django 5.1.3 on 2024-11-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BRDName', models.CharField(max_length=50, verbose_name='brand name')),
                ('BRDDesk', models.TextField(blank=True, max_length=200, null=True, verbose_name='brand description')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Varient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VARName', models.CharField(max_length=50, verbose_name='varient name')),
                ('VARDesk', models.TextField(blank=True, max_length=200, null=True, verbose_name='varient description')),
            ],
            options={
                'verbose_name': 'varient',
                'verbose_name_plural': 'varients',
            },
        ),
    ]
